In [2]:
# Pytorch tutorial: 

# The basics of pytorch - very quickly ... 
# https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.htmlc

import torch
import numpy as np

In [10]:
data = [[1,2], [3,4]]

x_data = torch.tensor(data)
x_data

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])

In [13]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

np_array

array([[1, 2],
       [3, 4]])

In [14]:
torch.ones_like(x_data)

tensor([[1., 1.],
        [1., 1.]])

In [17]:
?torch.rand_like

Docstring:
rand_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

Returns a tensor with the same size as :attr:`input` that is filled with
random numbers from a uniform distribution on the interval :math:`[0, 1)`.
``torch.rand_like(input)`` is equivalent to
``torch.rand(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype of :attr:`input`.
    layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
        Default: if ``None``, defaults to the layout of :attr:`input`.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, defaults to the device of :attr:`input`.
 

In [55]:
g = torch.Generator().manual_seed(123)
torch.rand_like(x_data, dtype=torch.float)

tensor([[0.7111, 0.9325],
        [0.6130, 0.0117]])

In [56]:
?x_data.layout

Type:        layout
String form: torch.strided
File:        ~/.virtualenvs/torchy/lib/python3.9/site-packages/torch/__init__.py
Docstring:   <no docstring>


In [57]:
x_data.size()

torch.Size([2, 2])

In [58]:
x_data.dtype

torch.float32

In [59]:
g = torch.Generator().manual_seed(123)
torch.rand(x_data.size(), dtype=x_data.dtype,generator=g)

tensor([[0.2961, 0.5166],
        [0.2517, 0.6886]])

In [60]:
x_data.device 

device(type='cpu')

In [ ]:
# move to another device

if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [63]:
# concatenating tensors

tensor = torch.ones(1, 4)

tensor

tensor([[1., 1., 1., 1.]])

In [65]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [66]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
t1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
a = torch.ones(4, 4)

# matrix multip
y1 = a @ a.T
y1_1 = a.matmul(a.T)

y1_2 = torch.zeros(y1_1.shape)
torch.matmul(a, a.T, out=y1_2)

# element wise multi
y2_1 = a * a 
y2_2 = a.mul(a)

y2_3 = torch.zeros(y2_2.shape)
torch.mul(a, a.T, out=y2_3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [91]:
y2_3

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [95]:
total = tensor.sum()
total

tensor(16.)

In [96]:
total.item()

16.0

In [97]:
# inplace operations
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
